export default {
  address: {
    city: 'Stad',
    city_short: 'stad',
    clear: 'Duidelik',
    country: 'Land',
    country_short: 'land',
    email: 'E-pos',
    email_short: 'epos',
    name: 'Naam',
    name_short: 'naam',
    nothing: 'Niks',
    phone: 'Foon',
    phone_short: 'foon',
    save: 'Save',
    state: 'Staat',
    state_short: 'staat',
    street1: 'Straat 1',
    street1_short: 'straat1',
    street2: 'Straat 2',
    street2_short: 'straat2',
    zip: 'Poskode',
    zip_short: 'poskode',
  },
  creditCard: {
    clear: 'Duidelik',
    expDate: 'Vervaldatum Datum',
    expDate_short: 'vervaldatumDatum',
    expMonth: 'Vervaldatum Maand',
    expMonth_short: 'vervaldatumMaand',
    expYear: 'Vervaldatum Jaar',
    expYear_short: 'vervaldatumJaar',
    name: 'Naam op kaart',
    name_short: 'naam',
    nothing: 'Niks',
    number: 'Kaart nommer',
    number_short: 'nommer',
    cvv: 'CVV',
    cvv_short: 'cvv',
    save: 'Bespaar Kredietkaart',
  },
  login: {
    accountId: 'Rekening ID',
    accountId_short: 'rekeningId',
    clear: 'Duidelik',
    nothing: 'Niks',
    password: 'Wagwoord',
    password_short: 'wagwoord',
    submit: 'Indien',
    username: 'Gebruikersnaam',
    username_short: 'gebruikersnaam',
  },
  passwordReset: {
    clear: 'Duidelik',
    email: 'E-pos',
    email_short: 'epos',
    confirmNewPass: 'Bevestig Nuwe Wagwoord',
    confirmNewPass_short: 'bevestigWagwoord',
    newPass: 'Nuwe Wagwoord',
    newPass_short: 'nuweWagwoord',
    nothing: 'Niks',
    oldPass: 'Huidige Sleutelwoord',
    oldPass_short: 'huidigeSleutelwoord',
    submit: 'Indien',
  },
}