export default {
  address: {
    city: 'Stad',
    clear: 'Duidelik',
    country: 'Land',
    email: 'E-pos',
    name: 'Naam',
    nothing: 'Niks',
    phone: 'Foon',
    save: 'Save',
    state: 'Staat',
    street1: 'Straat 1',
    street2: 'Straat 2',
    zip: 'Poskode',
  },
  creditCard: {
    clear: 'Duidelik',
    expDate: 'Vervaldatum Datum',
    expMonth: 'Vervaldatum Maand',
    expYear: 'Vervaldatum Jaar',
    name: 'Naam op kaart',
    nothing: 'Niks',
    number: 'Kaart nommer',
    cvv: 'CVV',
    save: 'Bespaar Kredietkaart',
  },
  login: {
    accountId: 'Rekening ID',
    clear: 'Duidelik',
    nothing: 'Niks',
    password: 'Wagwoord',
    submit: 'Indien',
    username: 'Gebruikersnaam',
  },
  passwordReset: {
    clear: 'Duidelik',
    email: 'E-pos',
    confirmNewPass: 'Bevestig Nuwe Wagwoord',
    newPass: 'Nuwe Wagwoord',
    nothing: 'Niks',
    oldPass: 'huidige Sleutelwoord',
    submit: 'Indien',
  },
}