export default {
  address: {
    city: 'City',
    clear: 'Clear',
    country: 'Country',
    email: 'Email',
    name: 'Name',
    nothing: 'Nothing',
    phone: 'Phone',
    save: 'Save',
    state: 'State',
    street1: 'Street 1',
    street2: 'Street 2',
    zip: 'Zip',
  },
  creditCard: {
    clear: 'Clear',
    expDate: 'Expiration Date',
    expMonth: 'Expiration Month',
    expYear: 'Expiration Year',
    name: 'Name on Card',
    nothing: 'Nothing',
    number: 'Card Number',
    cvv: 'CVV',
    save: 'Save Credit Card',
  },
  login: {
    accountId: 'Account ID',
    clear: 'Clear',
    nothing: 'Nothing',
    password: 'Password',
    submit: 'Submit',
    username: 'Username',
  },
  passwordReset: {
    clear: 'Clear',
    email: 'Email',
    confirmNewPass: 'Confirm New Password',
    newPass: 'New Password',
    nothing: 'Nothing',
    oldPass: 'Current Password',
    submit: 'Submit',
  },
}