export default {
  address: {
    city: 'City',
    city_short: 'city',
    clear: 'Clear',
    country: 'Country',
    country_short: 'country',
    email: 'Email',
    email_short: 'email',
    name: 'Name',
    name_short: 'name',
    nothing: 'Nothing',
    phone: 'Phone',
    phone_short: 'phone',
    save: 'Save',
    state: 'State',
    state_short: 'state',
    street1: 'Street 1',
    street1_short: 'streetOne',
    street2: 'Street 2',
    street2_short: 'streetTwo',
    zip: 'Zip',
    zip_short: 'zip',
  },
  creditCard: {
    clear: 'Clear',
    expDate: 'Expiration Date',
    expDate_short: 'expiration-date',
    expMonth: 'Expiration Month',
    expMonth_short: 'expiration-month',
    expYear: 'Expiration Year',
    expYear_short: 'expiration-year',
    name: 'Name on Card',
    name_short: 'cardholderName',
    nothing: 'Nothing',
    number: 'Card Number',
    number_short: 'cardNumber',
    cvv: 'CVV',
    cvv_short: 'cvv',
    save: 'Save Credit Card',
  },
  login: {
    accountId: 'Account ID',
    accountId_short: 'accountId',
    clear: 'Clear',
    nothing: 'Nothing',
    password: 'Password',
    password_short: 'password',
    submit: 'Submit',
    username: 'Username',
    username_short: 'username',
  },
  passwordReset: {
    clear: 'Clear',
    email: 'Email',
    email_short: 'email',
    confirmNewPass: 'Confirm New Password',
    confirmNewPass_short: 'confirmNewPassword',
    newPass: 'New Password',
    newPass_short: 'newPassword',
    nothing: 'Nothing',
    oldPass: 'Current Password',
    oldPass_short: 'oldPassword',
    submit: 'Submit',
  },
}
